FROM node:16

ENV CI=true

WORKDIR /app

COPY package.json ./

RUN npm install

COPY ./ ./

#install R and packages
RUN apt update
RUN apt-get -y install libcurl4-openssl-dev
RUN apt-get -y install libxml2-dev
RUN apt-get -y install libssl-dev
RUN apt-get -y install r-base
RUN apt-get install -y -qq r-cran-rcurl
RUN apt-get install -y -qq r-cran-xml
RUN apt-get install -y -qq r-cran-httr
RUN R -e "install.packages(c('haploR'),dependencies=TRUE,repos='http://cran.rstudio.com/')"

#remove windows line endings
RUN apt-get install dos2unix
RUN dos2unix pipeline_scripts/haploR.sh
RUN dos2unix pipeline_scripts/HaploReg.R
RUN dos2unix pipeline_scripts/Regulome.R

RUN chmod 775 pipeline_scripts/haploR.sh
RUN chmod 775 pipeline_scripts/HaploReg.R
RUN chmod 775 pipeline_scripts/Regulome.R

#RUN yarn run build
CMD [ "npm", "run", "start:dev" ]
